### ISSUE TITLE
How do I invite the bot?

### ISSUE THREAD

**Issue by ErikXx0720** [Rosee-Z/Discord-Account-Dispenser#1]
I'm really sorry, but I am absolutely brand new here. Just wondering if I could get some explanation on how to "invite" the bot. Thank you :)

**Comment by Rosee-Z** [comment]
you have to use the discord developer portal: https://discord.com/developers/applications
when you're logged into the developer portal make a new application and then hit the bot page take your bots token from there
then to invite the bot go to the OAuth2 panel click bot in the scopes https://kurwa.club/u/DXdvg.png 
give it whatever perms that you want.
then just look at the scopes section and it'll give you a link to invite your bot
