### ISSUE TITLE
Actually running the bot..

### ISSUE THREAD

**Issue by ErikXx0720** [Rosee-Z/Discord-Account-Dispenser#2]
Obviously the bot is already in my server, but how do I "run it" with the code? Once again, I'm sorry for my lack of knowledge.

**Comment by Rosee-Z** [comment]
goto the folder where you have the bot saved and then type "cmd" in the top bar 
https://ROSSE.acrack.site/Rosee_does_crack/xtVE6U6a
hit enter then a console will pop up
in the console type "python bot.py"

**Comment by Rosee-Z** [comment]
or whatever the file name you're tryina to run i think it was main.py
