### ISSUE TITLE
I finally came back to this, quick error

### ISSUE THREAD

**Issue by ErikXx0720** [Rosee-Z/Discord-Account-Dispenser#3]
Task exception was never retrieved
future: <Task finished name='Task-12' coro=<lolhaha() done, defined at D:\Downloads\Discord-Account-Dispenser-main\Discord-Account-Dispenser-main\index.py:429> exception=AttributeError("'NoneType' object has no attribute 'roles'")>
Traceback (most recent call last):
  File "D:\Downloads\Discord-Account-Dispenser-main\Discord-Account-Dispenser-main\index.py", line 430, in lolhaha
    for role in client.get_guild(serverid).roles:
AttributeError: 'NoneType' object has no attribute 'roles'

**Comment by Rosee-Z** [comment]
ill fix it

**Comment by Rosee-Z** [comment]
fixed

**Comment by ErikXx0720** [comment]
looks amazing!!

**Comment by Rosee-Z** [comment]
(: 👍 🥇 
remember to share my github xx
